//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverythingQuickSearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EverythingQuickSearch.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Everything_Error_MissingDll_MessageBox_CloseButtonText {
            get {
                return ResourceManager.GetString("Everything_Error_MissingDll_MessageBox_CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Everything_Error_MissingDll_MessageBox_PrimaryButtonText {
            get {
                return ResourceManager.GetString("Everything_Error_MissingDll_MessageBox_PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything64.dll is missing!.
        /// </summary>
        public static string Everything_Error_MissingDll_MessageBox_TextBlock {
            get {
                return ResourceManager.GetString("Everything_Error_MissingDll_MessageBox_TextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Everything64.dll from Everything-SDK.zip\dll\ and place it next to &quot;EverythingQuickSearch.exe&quot;.
        /// </summary>
        public static string Everything_Error_MissingDll_MessageBox_TextBlock2 {
            get {
                return ResourceManager.GetString("Everything_Error_MissingDll_MessageBox_TextBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Everything-SDK.zip.
        /// </summary>
        public static string Everything_Error_MissingDll_MessageBox_UrlText {
            get {
                return ResourceManager.GetString("Everything_Error_MissingDll_MessageBox_UrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string SearchWindow_CategoryButton_All {
            get {
                return ResourceManager.GetString("SearchWindow_CategoryButton_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressed.
        /// </summary>
        public static string SearchWindow_CategoryButton_Compressed {
            get {
                return ResourceManager.GetString("SearchWindow_CategoryButton_Compressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string SearchWindow_CategoryButton_Documents {
            get {
                return ResourceManager.GetString("SearchWindow_CategoryButton_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executables.
        /// </summary>
        public static string SearchWindow_CategoryButton_Executables {
            get {
                return ResourceManager.GetString("SearchWindow_CategoryButton_Executables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string SearchWindow_CategoryButton_Files {
            get {
                return ResourceManager.GetString("SearchWindow_CategoryButton_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string SearchWindow_CategoryButton_Folders {
            get {
                return ResourceManager.GetString("SearchWindow_CategoryButton_Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string SearchWindow_CategoryButton_Images {
            get {
                return ResourceManager.GetString("SearchWindow_CategoryButton_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string SearchWindow_CategoryButton_Videos {
            get {
                return ResourceManager.GetString("SearchWindow_CategoryButton_Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t change category when
        ///regex filtering is enabled.
        /// </summary>
        public static string SearchWindow_FilterButton_ToolTip_RegexEnabled {
            get {
                return ResourceManager.GetString("SearchWindow_FilterButton_ToolTip_RegexEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string SearchWindow_Item_Actions_OpenFile {
            get {
                return ResourceManager.GetString("SearchWindow_Item_Actions_OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file location.
        /// </summary>
        public static string SearchWindow_Item_Actions_OpenFileLocation {
            get {
                return ResourceManager.GetString("SearchWindow_Item_Actions_OpenFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as administrator.
        /// </summary>
        public static string SearchWindow_Item_Actions_RunAsAdministrator {
            get {
                return ResourceManager.GetString("SearchWindow_Item_Actions_RunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as path.
        /// </summary>
        public static string SearchWindow_Item_ContextMenu_CopyAsPath {
            get {
                return ResourceManager.GetString("SearchWindow_Item_ContextMenu_CopyAsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy folder path.
        /// </summary>
        public static string SearchWindow_Item_ContextMenu_CopyFolderPath {
            get {
                return ResourceManager.GetString("SearchWindow_Item_ContextMenu_CopyFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string SearchWindow_Item_ContextMenu_Open {
            get {
                return ResourceManager.GetString("SearchWindow_Item_ContextMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open path.
        /// </summary>
        public static string SearchWindow_Item_ContextMenu_OpenPath {
            get {
                return ResourceManager.GetString("SearchWindow_Item_ContextMenu_OpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified:.
        /// </summary>
        public static string SearchWindow_Item_Details_LastModified {
            get {
                return ResourceManager.GetString("SearchWindow_Item_Details_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        public static string SearchWindow_Item_Details_Location {
            get {
                return ResourceManager.GetString("SearchWindow_Item_Details_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string SearchWindow_Item_Details_Resolution {
            get {
                return ResourceManager.GetString("SearchWindow_Item_Details_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string SearchWindow_Item_Details_Size {
            get {
                return ResourceManager.GetString("SearchWindow_Item_Details_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found for.
        /// </summary>
        public static string SearchWindow_Search_NoResults {
            get {
                return ResourceManager.GetString("SearchWindow_Search_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string SearchWindow_SortBy_Ascending {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string SearchWindow_SortBy_Attributes {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date accessed.
        /// </summary>
        public static string SearchWindow_SortBy_DateAccessed {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_DateAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string SearchWindow_SortBy_DateCreated {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date modified.
        /// </summary>
        public static string SearchWindow_SortBy_DateModified {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date recently changed.
        /// </summary>
        public static string SearchWindow_SortBy_DateRecentlyChanged {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_DateRecentlyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date run.
        /// </summary>
        public static string SearchWindow_SortBy_DateRun {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_DateRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string SearchWindow_SortBy_Descending {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string SearchWindow_SortBy_Extension {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File list filename.
        /// </summary>
        public static string SearchWindow_SortBy_FileListFileName {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_FileListFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SearchWindow_SortBy_Name {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string SearchWindow_SortBy_Path {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run count.
        /// </summary>
        public static string SearchWindow_SortBy_RunCount {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_RunCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SearchWindow_SortBy_Size {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SearchWindow_SortBy_Type {
            get {
                return ResourceManager.GetString("SearchWindow_SortBy_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto update.
        /// </summary>
        public static string TrayIcon_AutoUpdate {
            get {
                return ResourceManager.GetString("TrayIcon_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string TrayIcon_CheckForUpdate {
            get {
                return ResourceManager.GetString("TrayIcon_CheckForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayIcon_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start on login.
        /// </summary>
        public static string TrayIcon_StartOnLogin {
            get {
                return ResourceManager.GetString("TrayIcon_StartOnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        public static string TrayIcon_Version {
            get {
                return ResourceManager.GetString("TrayIcon_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit GitHub.
        /// </summary>
        public static string TrayIcon_VisitGitHub {
            get {
                return ResourceManager.GetString("TrayIcon_VisitGitHub", resourceCulture);
            }
        }
    }
}
